### PR TITLE
Disable signup

### PR DESCRIPTION
**Pull request by louisbranch**
Closes: https://github.com/manifoldco/engineering/issues/5098

### CODE REVIEW

**Comment by jbowes** [comment]
What's the output look like?

**Comment by luizbranco** [comment]
```
$ ./torus signup
Torus is no longer accepting signups.
```

**Comment by luizbranco** [comment]
That won't pass vet though. I can print a regular exist and exit with -1

**Review by jbowes — APPROVED** [review]

**Comment by trulyronak** [comment]
I just discovered this incredible project, what happened?

**Pull request merged**
