### PR TITLE
Add support for High Sierra via Brew

### PR DESCRIPTION
**Pull request by ianlivingstone**

### CODE REVIEW

**Comment by pmdarrow** [comment]
Should it also be possible to install torus on High Sierra without the brew bottle? This is what I get now:

```
$ brew install manifoldco/brew/torus
==> Installing torus from manifoldco/brew
==> Downloading https://github.com/manifoldco/torus-cli/archive/v0.24.2.tar.gz
Already downloaded: /Users/peter/Library/Caches/Homebrew/torus-0.24.2.tar.gz
==> Cloning https://github.com/jteeuwen/go-bindata.git
Updating /Users/peter/Library/Caches/Homebrew/torus--github.com-jteeuwen-go-bindata--git
==> Checking out revision a0ff2567cfb70903282db057e799fd826784d41d
==> go install github.com/jteeuwen/go-bindata/...
==> make binary-darwin-amd64 VERSION=0.24.2 BYPASS_GO_CHECK=yes
Last 15 lines from /Users/peter/Library/Logs/Homebrew/torus/02.make:
github.com/manifoldco/torus-cli/vendor/github.com/facebookgo/stats
github.com/manifoldco/torus-cli/vendor/github.com/blang/semver
github.com/manifoldco/torus-cli/vendor/github.com/nightlyone/lockfile
github.com/manifoldco/torus-cli/dirprefs
github.com/manifoldco/torus-cli/gatekeeper/apitypes
github.com/manifoldco/torus-cli/vendor/github.com/manifoldco/ansiwrap
github.com/manifoldco/torus-cli/vendor/github.com/natefinch/lumberjack
github.com/manifoldco/torus-cli/envelope
github.com/manifoldco/torus-cli/apitypes
github.com/manifoldco/torus-cli/errs
github.com/manifoldco/torus-cli/daemon/db
github.com/manifoldco/torus-cli/daemon/session
github.com/manifoldco/torus-cli/daemon/crypto
go install net: open /usr/local/Cellar/go/1.9.1/libexec/pkg/darwin_amd64/net.a: operation not permitted
make: *** [binary-darwin-amd64] Error 1

If reporting this issue please do so at (not Homebrew/brew or Homebrew/core):
https://github.com/manifoldco/homebrew-brew/issues
```

**Comment by ianlivingstone** [comment]
> Should it also be possible to install torus on High Sierra without the brew bottle? This is what I get now:

Yeah, it should be - I'll take a gander at this bug, it happens on sierra and el capitan as well.

**Comment by ianlivingstone** [comment]
I opened a subsequent issue to investigate building from source.

**Comment by pmdarrow** [comment]
@ianlivingstone do you know why brew prefers to install from source on High Sierra even with this change?

**Comment by ianlivingstone** [comment]
> @ianlivingstone do you know why brew prefers to install from source on High Sierra even with this change?

The bottles haven't been published yet (pending a release of Torus), once that's done it should just install from the bottle!

**Pull request merged**
