### PR TITLE
The great worklog ui revamp

### PR DESCRIPTION
**Pull request by jbowes**
Final changes needed for our new worklog ui (except line wrapping ;) )

The bulk of this is just the rewrite of `cmd/worklog.go`, but there are a few secondary bits too:
- minor changes to `ui` and `promptui`
- split out user vs machine keyring rotation types
- remove the worklog result type (using details and error results instead).

### CODE REVIEW

**Comment by jbowes** [comment]
Example (use your imagination for the colors and formatting):
```
[jbowes@shoggoth torus-cli]$ ./torus worklog list
Attempting to login with email: james@arigato.sh
invite Invites ready for approval to the james org:
  0j75q8vv6cgb3b8 james1 <james+1@arigato.sh>
  0g0v8fagz2ahz3r james2 <james+2@arigato.sh>

keyring Machines missing granted access to keyrings in the james org:
  22ukg8jgxr31u08 foobar-tdgagdpy

secret Secrets that should be rotated in the james org:
  06xmx7tcz49vzq8 /james/coolproj/dev-james/default/*/*/post_key_revoke
  072p27rwvx1fpyr /james/coolproj/dev-james/default/*/*/foo
  05fq5m58avvejeg /james/coolproj/dev-james/default/*/*/other
  06qkapz4a5zw2w8 /james/coolproj/dev-james/default/*/*/bip1
  05n9a3gvxa4zgrr /james/coolproj/dev-james/default/*/*/bip2
  078d9ym8uwk7d98 /james/coolproj/foo/*/*/*/bar
[jbowes@shoggoth torus-cli]$ ./torus worklog view 22ukg8jgxr31u08
22ukg8jgxr31u08 foobar-tdgagdpy
  foobar-tdgagdpy is missing granted access to secrets in the james org.
  Secrets in the following paths are affected:
    /james/coolproj/foo/*/*/*
    /james/coolproj/dev-james/default/*/*
[jbowes@shoggoth torus-cli]$ ./torus worklog resolve
invite Invites ready for approval to the james org:
  ✗ 0j75q8vv6cgb3b8 Approve invite for james1 <james+1@arigato.sh>? [y/N] n
  ✗ 0g0v8fagz2ahz3r Approve invite for james2 <james+2@arigato.sh>? [y/N] n

keyring Machines missing granted access to keyrings in the james org:
  ✔ 22ukg8jgxr31u08 Keyring access for machine foobar-tdgagdpy has been reconciled.

secret Secrets that should be rotated in the james org:
  ⚠ 06xmx7tcz49vzq8 Please set a new value for
      /james/coolproj/dev-james/default/*/*/post_key_revoke
  ⚠ 06qkapz4a5zw2w8 Please set a new value for
      /james/coolproj/dev-james/default/*/*/bip1
  ⚠ 05n9a3gvxa4zgrr Please set a new value for
      /james/coolproj/dev-james/default/*/*/bip2
  ⚠ 072p27rwvx1fpyr Please set a new value for
      /james/coolproj/dev-james/default/*/*/foo
  ⚠ 05fq5m58avvejeg Please set a new value for
      /james/coolproj/dev-james/default/*/*/other
  ⚠ 078d9ym8uwk7d98 Please set a new value for
      /james/coolproj/foo/*/*/*/bar
[jbowes@shoggoth torus-cli]$ ./torus worklog view 0j75q8vv6cgb3b8
0j75q8vv6cgb3b8 james1 <james+1@arigato.sh>
  The invite for james to the james org is ready for approval.
  They will be invited to the following teams:
    member
[jbowes@shoggoth torus-cli]$ ./torus worklog resolve 0j75q8vv6cgb3b8
✔ 0j75q8vv6cgb3b8 Invite approved for james1 <james+1@arigato.sh>
[jbowes@shoggoth torus-cli]$ ./torus worklog resolve
invite Invites ready for approval to the james org:
  ✔ 0g0v8fagz2ahz3r Approve invite for james2 <james+2@arigato.sh>? [y/N] y
  ✔ 0g0v8fagz2ahz3r Invite approved for james2 <james+2@arigato.sh>

secret Secrets that should be rotated in the james org:
  ⚠ 06xmx7tcz49vzq8 Please set a new value for
      /james/coolproj/dev-james/default/*/*/post_key_revoke
  ⚠ 05fq5m58avvejeg Please set a new value for
      /james/coolproj/dev-james/default/*/*/other
  ⚠ 06qkapz4a5zw2w8 Please set a new value for
      /james/coolproj/dev-james/default/*/*/bip1
  ⚠ 05n9a3gvxa4zgrr Please set a new value for
      /james/coolproj/dev-james/default/*/*/bip2
  ⚠ 072p27rwvx1fpyr Please set a new value for
      /james/coolproj/dev-james/default/*/*/foo
  ⚠ 078d9ym8uwk7d98 Please set a new value for
      /james/coolproj/foo/*/*/*/bar
[jbowes@shoggoth torus-cli]$ ./torus worklog view 06xmx7tcz49vzq8
06xmx7tcz49vzq8 /james/coolproj/dev-james/default/*/*/post_key_revoke
  The value for this secret should be rotated for the following reasons:
    james3 changed their encryption key.
    james4 was removed from the org.
```

**Comment by ianlivingstone** [comment]
> keyring Machines missing granted access to keyrings in the james org:

Is there a way for us to message that a Machine is missing access to a secret instead of having to explain or surface the concept of keyrings?

**Comment by jbowes** [comment]
> Is there a way for us to message that a Machine is missing access to a secret instead of having to explain or surface the concept of keyrings?

Yeah i think we can say:
```
Machines missing granted access to secrets in the james org:

Error reconciling secret access:

Secret access for machine foobar has been reconciled.
```

and make the printed type `secret`.

We then have `secret` for user keyrings, machine keyrings, and secret rotation. `secret` is the category, and those specific types are the groups.

How's that sound?

**Comment by ianlivingstone** [comment]
Sounds great!

**Comment by jbowes** [comment]
updated

**Pull request merged**
